/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.UI;

/**
 *
 * @author ispaycy
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        BG = new javax.swing.JPanel();
        Tool = new javax.swing.JToolBar();
        New = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        SaveAs = new javax.swing.JButton();
        Open = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        Run = new javax.swing.JButton();
        CleanTerm = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Files = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Output = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Editor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        NewFileCont = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        OpenFileCont = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        SaveFileCont = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        SaveAsFileCont = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        Instructions = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Examples = new javax.swing.JMenu();
        Sequence = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Selection = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Repetition = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Copy = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        Cut = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        Paste = new javax.swing.JMenuItem();
        About = new javax.swing.JMenu();
        AboutCont = new javax.swing.JMenuItem();

        jButton2.setText("newf");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPreferredSize(new java.awt.Dimension(35, 35));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(1366, 768));

        BG.setLayout(new java.awt.BorderLayout());

        Tool.setBackground(new java.awt.Color(51, 51, 51));
        Tool.setBorder(null);
        Tool.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Tool.setRollover(true);
        Tool.setName(""); // NOI18N
        Tool.setPreferredSize(new java.awt.Dimension(75, 75));
        Tool.setRequestFocusEnabled(false);

        New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newF.png"))); // NOI18N
        New.setFocusable(false);
        New.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        New.setPreferredSize(new java.awt.Dimension(50, 75));
        New.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        Tool.add(New);

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        Save.setFocusable(false);
        Save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Save.setPreferredSize(new java.awt.Dimension(50, 75));
        Save.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Tool.add(Save);

        SaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/saveAs.png"))); // NOI18N
        SaveAs.setFocusable(false);
        SaveAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveAs.setPreferredSize(new java.awt.Dimension(50, 75));
        SaveAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsActionPerformed(evt);
            }
        });
        Tool.add(SaveAs);

        Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        Open.setFocusable(false);
        Open.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Open.setPreferredSize(new java.awt.Dimension(50, 75));
        Open.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        Tool.add(Open);

        jSeparator9.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator9.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator9.setPreferredSize(new java.awt.Dimension(10, 9));
        Tool.add(jSeparator9);

        Run.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/run.png"))); // NOI18N
        Run.setFocusable(false);
        Run.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Run.setPreferredSize(new java.awt.Dimension(50, 75));
        Run.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });
        Tool.add(Run);

        CleanTerm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clean.png"))); // NOI18N
        CleanTerm.setFocusable(false);
        CleanTerm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CleanTerm.setPreferredSize(new java.awt.Dimension(50, 75));
        CleanTerm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CleanTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanTermActionPerformed(evt);
            }
        });
        Tool.add(CleanTerm);

        BG.add(Tool, java.awt.BorderLayout.WEST);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setLayout(new java.awt.BorderLayout());

        Files.setBackground(new java.awt.Color(44, 44, 44));
        Files.setPreferredSize(new java.awt.Dimension(200, 678));
        Files.setRequestFocusEnabled(false);

        javax.swing.GroupLayout FilesLayout = new javax.swing.GroupLayout(Files);
        Files.setLayout(FilesLayout);
        FilesLayout.setHorizontalGroup(
            FilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        FilesLayout.setVerticalGroup(
            FilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );

        jPanel4.add(Files, java.awt.BorderLayout.WEST);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 678));
        jPanel5.setLayout(new java.awt.BorderLayout());

        Output.setBackground(new java.awt.Color(34, 34, 34));
        Output.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Output.setPreferredSize(new java.awt.Dimension(1366, 200));
        Output.setRequestFocusEnabled(false);
        Output.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jTextArea1.setBackground(new java.awt.Color(34, 34, 34));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        Output.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.add(Output, java.awt.BorderLayout.SOUTH);

        Editor.setBackground(new java.awt.Color(34, 34, 34));
        Editor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Editor.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(34, 34, 34));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jEditorPane1.setBackground(new java.awt.Color(34, 34, 34));
        jEditorPane1.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jEditorPane1);

        Editor.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.add(Editor, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        BG.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(BG, java.awt.BorderLayout.CENTER);

        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Menu.setForeground(new java.awt.Color(51, 51, 51));
        Menu.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        Menu.setMinimumSize(new java.awt.Dimension(160, 30));
        Menu.setPreferredSize(new java.awt.Dimension(160, 40));

        File.setForeground(new java.awt.Color(51, 51, 51));
        File.setText("File");

        NewFileCont.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        NewFileCont.setText("New File");
        File.add(NewFileCont);
        File.add(jSeparator8);

        OpenFileCont.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        OpenFileCont.setText("Open File");
        File.add(OpenFileCont);
        File.add(jSeparator7);

        SaveFileCont.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SaveFileCont.setText("Save File");
        File.add(SaveFileCont);
        File.add(jSeparator6);

        SaveAsFileCont.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SaveAsFileCont.setText("Safe File As");
        File.add(SaveAsFileCont);

        Menu.add(File);

        Help.setForeground(new java.awt.Color(51, 51, 51));
        Help.setText("Help");

        Instructions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Instructions.setText("Instructions");
        Instructions.setAutoscrolls(true);
        Instructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructionsActionPerformed(evt);
            }
        });
        Help.add(Instructions);
        Help.add(jSeparator1);

        Examples.setText("Examples");
        Examples.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        Sequence.setText("Sequence Control Structures");
        Sequence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SequenceActionPerformed(evt);
            }
        });
        Examples.add(Sequence);
        Examples.add(jSeparator2);

        Selection.setText("Selection Control Structures");
        Examples.add(Selection);
        Examples.add(jSeparator3);

        Repetition.setText("Repetition Control Structures");
        Examples.add(Repetition);

        Help.add(Examples);

        Menu.add(Help);

        Edit.setForeground(new java.awt.Color(51, 51, 51));
        Edit.setText("Edit");

        Copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Copy.setText("Copy");
        Copy.setPreferredSize(new java.awt.Dimension(76, 25));
        Edit.add(Copy);
        Edit.add(jSeparator5);

        Cut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Cut.setText("Cut");
        Edit.add(Cut);
        Edit.add(jSeparator4);

        Paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Paste.setText("Paste");
        Paste.setPreferredSize(new java.awt.Dimension(76, 25));
        Edit.add(Paste);

        Menu.add(Edit);

        About.setForeground(new java.awt.Color(51, 51, 51));
        About.setText("About");

        AboutCont.setText("About this software");
        About.add(AboutCont);

        Menu.add(About);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveAsActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RunActionPerformed

    private void InstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstructionsActionPerformed

    private void SequenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SequenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SequenceActionPerformed

    private void CleanTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanTermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CleanTermActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu About;
    private javax.swing.JMenuItem AboutCont;
    private javax.swing.JPanel BG;
    private javax.swing.JButton CleanTerm;
    private javax.swing.JMenuItem Copy;
    private javax.swing.JMenuItem Cut;
    private javax.swing.JMenu Edit;
    private javax.swing.JPanel Editor;
    private javax.swing.JMenu Examples;
    private javax.swing.JMenu File;
    private javax.swing.JPanel Files;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem Instructions;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton New;
    private javax.swing.JMenuItem NewFileCont;
    private javax.swing.JButton Open;
    private javax.swing.JMenuItem OpenFileCont;
    private javax.swing.JPanel Output;
    private javax.swing.JMenuItem Paste;
    private javax.swing.JMenuItem Repetition;
    private javax.swing.JButton Run;
    private javax.swing.JButton Save;
    private javax.swing.JButton SaveAs;
    private javax.swing.JMenuItem SaveAsFileCont;
    private javax.swing.JMenuItem SaveFileCont;
    private javax.swing.JMenuItem Selection;
    private javax.swing.JMenuItem Sequence;
    private javax.swing.JToolBar Tool;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
